INSERT INTO member(EMAIL, PASSWORD, ROLE, NICK_NAME, MEMBER_NAME, MEMBER_TYPE)
VALUES ('mason1@gmail.com', 'aaaa1111!', 'ADMIN', '관리자1', '이대겸', 'DEFAULT');

INSERT INTO member(EMAIL, PASSWORD, ROLE, NICK_NAME, MEMBER_NAME, MEMBER_TYPE)
VALUES ('mason2@gmail.com', 'aaaa1111!', 'ADMIN', '관리자1_2', '이대겸', 'DEFAULT');

INSERT INTO member(EMAIL, PASSWORD, ROLE, NICK_NAME, MEMBER_NAME, MEMBER_TYPE)
VALUES ('1013aq@gmail.com', 'aaaa1111!', 'ADMIN', '관리자2', '정동규', 'DEFAULT');
-- SELECT * FROM MEMBER